### ISSUE TITLE
Month indicator should not always show the startDate month when scrolled to another month. 

### ISSUE THREAD

**Issue by gregwym** [ultranano/UltraWeekCalendar#1]
![image](https://user-images.githubusercontent.com/510089/28251352-2247e7da-6a30-11e7-91a6-ae7703442932.png)

![image](https://user-images.githubusercontent.com/510089/28251361-583e2c5a-6a30-11e7-80c6-603cdef1d776.png)

1. Create a `UltraWeekCalendar` with `startDate` and `endDate` in different month. 
2. Scroll to a month that's later than `startDate`. 
3. The month indicator is not updated. 

User would think they are picking date inside the `startDate` month when they are actually in a different month. This can really be an issue when the `startDate` and `endDate` are few months apart.

**Comment by ultranano** [comment]
Fixed on 0.1.3
